### ISSUE TITLE
Format DateTime values in templates

### ISSUE THREAD

**Issue by JanLenoch** [Kentico/gatsby-starter-kentico-cloud#16]
### Motivation

The [project-reference.js](https://github.com/Kentico/gatsby-starter-kentico-cloud/blob/master/src/templates/project-reference.js) and [speaking-engagement.js](https://github.com/Kentico/gatsby-starter-kentico-cloud/blob/master/src/templates/speaking-engagement.js) templates display data of date & time content elements. They're currently formatted in the original ISO format.

### Design guidelines
Format the date & time information in a user-friendly way.

**Comment by justinh5** [comment]
I've worked with Gatsby a bit recently. I'll take this one.

**Comment by JanLenoch** [comment]
Implemented via #20 .
