### ISSUE TITLE
Demonstrate the use of Rich text elements

### ISSUE THREAD

**Issue by JanLenoch** [Kentico/gatsby-starter-kentico-cloud#23]
**Blocked:** https://github.com/Kentico/gatsby-source-kentico-cloud/issues/19

### Motivation

Once we create our [transformer plugin](https://github.com/Kentico/gatsby-source-kentico-cloud/issues/19), we should demonstrate the use of link resolvers and rich text resolvers in the starter site.

### Proposed solution

Make use of the Summary element of the Blogpost reference content type to demonstrate the resolvers.

**Comment by Simply007** [comment]
Split to #25 #26 #28
