### ISSUE TITLE
Use yarn instead of npm

### ISSUE THREAD

**Issue by Simply007** [Kentico/gatsby-starter-kentico-cloud#31]
### Motivation

When generating a new project based on this starter - the warning is showed up:

```
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
```

### Proposed solution

Use yarn instead of npm and remove package-lock.json

### Additional context

Mind updating the `Readme.md`.
The bootstrapped project is containing `package,json` and also `yarn.lock` file.

**Comment by JanLenoch** [comment]
Is Yarn capable of properly merging edits of package-lock.json made in two simultaneously running git branches? If yes, I'd vote for that too. Otherwise I'm not sure if it helped in such situations.

**Comment by Simply007** [comment]
Yarn was not implemented in referenced pull request - let's leave it opened.

**Comment by tom-raley** [comment]
Was this ever addressed? If not, I'd like to give it a go.
